Repository prgrms-web-devcourse-final-project/WEB5_7_2Jangs_BE, pull requests merged in 2025-07, with the labels that each got.

#7 Feat: GlobalExceptionHandler 구현
  src/main/java/io/ejangs/docsa/global/exception/ErrorResponse.java
  src/main/java/io/ejangs/docsa/global/exception/GlobalExceptionHandler.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/ErrorCode.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/UserErrorCode.java
Labels: ✨Feature

#16 Feat: 회원가입 인증코드 전송 API
  build.gradle
  src/main/java/io/ejangs/docsa/domain/auth/api/AuthController.java
  src/main/java/io/ejangs/docsa/domain/auth/app/AuthService.java
  src/main/java/io/ejangs/docsa/domain/auth/app/MailService.java
  src/main/java/io/ejangs/docsa/domain/auth/dto/request/SignupCodeRequest.java
  src/main/java/io/ejangs/docsa/domain/user/dao/UserRepository.java
  src/main/java/io/ejangs/docsa/global/config/CacheConfig.java
  src/main/java/io/ejangs/docsa/global/config/MailConfig.java
  src/main/java/io/ejangs/docsa/global/config/SecurityConfig.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/AuthErrorCode.java
  src/main/resources/application.yml
  src/test/java/io/ejangs/docsa/domain/auth/api/AuthControllerTest.java
  src/test/java/io/ejangs/docsa/domain/auth/app/AuthServiceTest.java
  src/test/java/io/ejangs/docsa/domain/auth/app/MailServiceTest.java
Labels: ✨Feature

#13 Feat: 이어서 작업하기 API
  src/main/java/io/ejangs/docsa/domain/block/entity/Block.java
  src/main/java/io/ejangs/docsa/domain/branch/api/BranchController.java
  src/main/java/io/ejangs/docsa/domain/branch/app/BranchService.java
  src/main/java/io/ejangs/docsa/domain/branch/dao/BranchRepository.java
  src/main/java/io/ejangs/docsa/domain/branch/dto/BranchCreateRequest.java
  src/main/java/io/ejangs/docsa/domain/branch/dto/BranchCreateResponse.java
  src/main/java/io/ejangs/docsa/domain/branch/entity/Branch.java
  src/main/java/io/ejangs/docsa/domain/branch/util/BranchMapper.java
  src/main/java/io/ejangs/docsa/domain/commit/app/CommitContentAssembler.java
  src/main/java/io/ejangs/docsa/domain/commit/dao/CommitBlockSequenceRepository.java
  src/main/java/io/ejangs/docsa/domain/commit/dao/CommitRepository.java
  src/main/java/io/ejangs/docsa/domain/document/dao/DocumentRepository.java
  src/main/java/io/ejangs/docsa/domain/save/dao/SaveRepository.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/BranchErrorCode.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/CommitErrorCode.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/DocumentErrorCode.java
  src/test/java/io/ejangs/docsa/domain/branch/api/BranchControllerTest.java
  src/test/java/io/ejangs/docsa/domain/branch/app/BranchServiceTest.java
  src/test/java/io/ejangs/docsa/domain/commit/app/CommitContentAssemblerTest.java
Labels: ✨Feature

#21 Fix: Merge이후 발생하는 문제 해결 & Test코드 수정
  src/main/java/io/ejangs/docsa/domain/branch/dto/BranchCreateResponse.java
  src/main/java/io/ejangs/docsa/domain/commit/app/CommitService.java
  src/main/java/io/ejangs/docsa/domain/document/app/DocumentService.java
  src/main/java/io/ejangs/docsa/domain/save/app/SaveService.java
  src/main/java/io/ejangs/docsa/domain/save/dao/SaveRepository.java
  src/main/java/io/ejangs/docsa/domain/save/save/SaveRepository.java
  src/main/java/io/ejangs/docsa/domain/save/util/SaveMapper.java
  src/test/java/io/ejangs/docsa/domain/auth/app/AuthServiceTest.java
  src/test/java/io/ejangs/docsa/domain/branch/api/BranchControllerTest.java
  src/test/java/io/ejangs/docsa/domain/branch/app/BranchServiceTest.java
  src/test/java/io/ejangs/docsa/domain/commit/api/CommitControllerMockTest.java
  src/test/java/io/ejangs/docsa/domain/commit/app/CommitServiceMockTest.java
  src/test/java/io/ejangs/docsa/domain/document/integration/DocumentRepositoryIntegrationTests.java
  src/test/java/io/ejangs/docsa/domain/document/integration/DocumentServiceIntegrationTests.java
  src/test/java/io/ejangs/docsa/domain/document/unit/DocumentServiceUnitTests.java
  src/test/resources/application.yml
Labels: 🔨Fix

#23 Feat: 인증 코드 검증 API
  src/main/java/io/ejangs/docsa/domain/auth/api/AuthController.java
  src/main/java/io/ejangs/docsa/domain/auth/app/AuthService.java
  src/main/java/io/ejangs/docsa/domain/auth/app/MailService.java
  src/main/java/io/ejangs/docsa/domain/auth/dto/request/CodeCheckRequest.java
  src/main/java/io/ejangs/docsa/domain/auth/dto/response/CodeCheckResponse.java
  src/main/java/io/ejangs/docsa/global/config/CacheConfig.java
  src/main/java/io/ejangs/docsa/global/config/SecurityConfig.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/AuthErrorCode.java
  src/main/resources/application.yml
  src/test/java/io/ejangs/docsa/domain/auth/api/AuthControllerTest.java
  src/test/java/io/ejangs/docsa/domain/auth/app/AuthServiceTest.java
Labels: ✨Feature

#47 Feat: 일괄 updatedAt 갱신 메서드
  src/main/java/io/ejangs/docsa/global/common/BaseEntity.java
  src/main/java/io/ejangs/docsa/global/util/RenewUpdatedAtHelper.java
Labels: ✨Feature

#37 Refactor: MongoDB 도입에 따라 바뀐 이어서 작업하기 API
  src/main/java/io/ejangs/docsa/domain/branch/api/BranchController.java
  src/main/java/io/ejangs/docsa/domain/branch/app/BranchService.java
  src/main/java/io/ejangs/docsa/domain/branch/entity/Branch.java
  src/main/java/io/ejangs/docsa/domain/branch/util/RenewUpdatedAtHelper.java
  src/main/java/io/ejangs/docsa/domain/commit/app/CommitContentAssembler.java
  src/main/java/io/ejangs/docsa/domain/doc/entity/Doc.java
  src/main/java/io/ejangs/docsa/domain/save/entity/Save.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/BlockErrorCode.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/CommitErrorCode.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/SaveErrorCode.java
  src/test/java/io/ejangs/docsa/domain/branch/api/BranchControllerTest.java
  src/test/java/io/ejangs/docsa/domain/branch/app/BranchServiceTest.java
  src/test/java/io/ejangs/docsa/domain/commit/app/CommitContentAssemblerTest.java
  src/test/resources/application.yml
Labels: ♻️Refactor

#40 Refactor: 문서 저장 api 구현 (mongo)
  src/main/java/io/ejangs/docsa/domain/branch/util/JsonConverter.java
  src/main/java/io/ejangs/docsa/domain/save/api/SaveController.java
  src/main/java/io/ejangs/docsa/domain/save/app/SaveService.java
  src/main/java/io/ejangs/docsa/domain/save/dao/SaveRepositoryAdapter.java
  src/main/java/io/ejangs/docsa/domain/save/dao/SaveRepositoryAdapterImpl.java
  src/main/java/io/ejangs/docsa/domain/save/document/SaveContent.java
  src/main/java/io/ejangs/docsa/domain/save/dto/SaveBlock.java
  src/main/java/io/ejangs/docsa/domain/save/dto/request/SaveUpdateRequest.java
  src/main/java/io/ejangs/docsa/domain/save/entity/Save.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/SaveErrorCode.java
  src/test/java/io/ejangs/docsa/domain/save/api/SaveControllerTest.java
  src/test/java/io/ejangs/docsa/domain/save/app/SaveServiceUnitTest.java
  src/test/java/io/ejangs/docsa/domain/save/dao/SaveRepositoryAdapterImplTest.java
Labels: ♻️Refactor

#52 Fix: 충돌 해결
  src/main/java/io/ejangs/docsa/domain/branch/app/BranchService.java
  src/main/java/io/ejangs/docsa/domain/branch/util/JsonConverter.java
  src/main/java/io/ejangs/docsa/domain/doc/app/DocService.java
  src/main/java/io/ejangs/docsa/domain/save/dto/SaveBlock.java
  src/test/java/io/ejangs/docsa/domain/branch/app/BranchServiceTest.java
  src/test/java/io/ejangs/docsa/domain/save/api/SaveControllerTest.java
  src/test/java/io/ejangs/docsa/domain/save/app/SaveServiceUnitTest.java
  src/test/java/io/ejangs/docsa/domain/save/dao/SaveRepositoryAdapterImplTest.java
  src/test/resources/application.yml
Labels: 🔨Fix

#49 Refactor: 연관관계 정립
  src/main/java/io/ejangs/docsa/domain/branch/entity/Branch.java
  src/main/java/io/ejangs/docsa/domain/commit/entity/Commit.java
  src/main/java/io/ejangs/docsa/domain/doc/entity/Doc.java
  src/main/java/io/ejangs/docsa/domain/doc/entity/Edge.java
  src/main/java/io/ejangs/docsa/domain/save/entity/Save.java
  src/main/java/io/ejangs/docsa/domain/user/entity/User.java
Labels: ♻️Refactor, 🧐Help wanted

#44 Feat: 로그인 API
  src/main/java/io/ejangs/docsa/domain/user/api/UserController.java
  src/main/java/io/ejangs/docsa/domain/user/app/UserService.java
  src/main/java/io/ejangs/docsa/domain/user/dao/mysql/UserRepository.java
  src/main/java/io/ejangs/docsa/domain/user/dto/request/UserLoginRequest.java
  src/main/java/io/ejangs/docsa/domain/user/dto/response/UserLoginResponse.java
  src/main/java/io/ejangs/docsa/domain/user/security/CustomAuthenticationEntryPoint.java
  src/main/java/io/ejangs/docsa/domain/user/security/CustomUserDetails.java
  src/main/java/io/ejangs/docsa/domain/user/security/CustomUserDetailsService.java
  src/main/java/io/ejangs/docsa/domain/user/util/SecurityContextUtil.java
  src/main/java/io/ejangs/docsa/global/config/SecurityConfig.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/AuthErrorCode.java
  src/test/java/io/ejangs/docsa/domain/user/app/UserServiceTest.java
  src/test/java/io/ejangs/docsa/domain/user/integration/UserIntegrationTest.java
Labels: ✨Feature

#58 Feat: 로그아웃 API
  src/main/java/io/ejangs/docsa/domain/user/api/UserController.java
  src/main/java/io/ejangs/docsa/domain/user/app/UserService.java
  src/main/java/io/ejangs/docsa/domain/user/dto/request/UserSignupRequest.java
  src/main/java/io/ejangs/docsa/domain/user/util/SecurityContextUtil.java
  src/main/java/io/ejangs/docsa/global/config/SecurityConfig.java
  src/test/java/io/ejangs/docsa/domain/user/app/UserServiceTest.java
  src/test/java/io/ejangs/docsa/domain/user/integration/UserIntegrationTest.java
Labels: ✨Feature

#57 Feat: 문서 하나의 기록 그래프 조회하기 API
  src/main/java/io/ejangs/docsa/domain/branch/api/BranchController.java
  src/main/java/io/ejangs/docsa/domain/branch/app/BranchService.java
  src/main/java/io/ejangs/docsa/domain/branch/dto/BranchDto.java
  src/main/java/io/ejangs/docsa/domain/branch/dto/request/BranchCreateRequest.java
  src/main/java/io/ejangs/docsa/domain/branch/dto/response/BranchCreateResponse.java
  src/main/java/io/ejangs/docsa/domain/branch/util/BranchMapper.java
  src/main/java/io/ejangs/docsa/domain/commit/dto/CommitDto.java
  src/main/java/io/ejangs/docsa/domain/doc/api/DocController.java
  src/main/java/io/ejangs/docsa/domain/doc/app/DocService.java
  src/main/java/io/ejangs/docsa/domain/doc/dao/mysql/DocRepository.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/EdgeDto.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/request/DocTitleRequest.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/response/CommitGraphResponse.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/response/DocCreateResponse.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/response/DocListSimpleResponse.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/response/DocTitleUpdateResponse.java
  src/main/java/io/ejangs/docsa/domain/doc/util/DocMapper.java
  src/main/java/io/ejangs/docsa/domain/doc/util/GraphMapper.java
  src/main/java/io/ejangs/docsa/domain/user/app/UserService.java
  src/test/java/io/ejangs/docsa/domain/branch/api/BranchControllerTest.java
  src/test/java/io/ejangs/docsa/domain/branch/app/BranchServiceTest.java
  src/test/java/io/ejangs/docsa/domain/doc/integration/DocRepositoryIntegrationTests.java
  src/test/java/io/ejangs/docsa/domain/doc/integration/DocServiceIntegrationTests.java
  src/test/java/io/ejangs/docsa/domain/doc/unit/DocControllerUnitTests.java
  src/test/java/io/ejangs/docsa/domain/doc/unit/DocServiceUnitTests.java
Labels: ✨Feature

#76 Fix: 병합 후 생기는 오류 해결
  src/main/java/io/ejangs/docsa/domain/commit/app/CommitService.java
  src/main/java/io/ejangs/docsa/domain/user/app/UserService.java
  src/test/java/io/ejangs/docsa/domain/commit/app/CommitServiceMockTest.java
  src/test/java/io/ejangs/docsa/domain/commit/app/GetCommitMockTest.java
  src/test/java/io/ejangs/docsa/domain/commit/util/CommitTestUtils.java
Labels: 🔨Fix

#71 Refactor: 인증코드 검증 API 공용화 (회원가입 + 비밀번호 변경)
  src/main/java/io/ejangs/docsa/domain/auth/app/AuthService.java
  src/main/java/io/ejangs/docsa/domain/auth/dto/request/CodeCheckRequest.java
  src/main/java/io/ejangs/docsa/domain/auth/model/CodeType.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/AuthErrorCode.java
  src/test/java/io/ejangs/docsa/domain/auth/api/AuthControllerTest.java
  src/test/java/io/ejangs/docsa/domain/auth/app/AuthServiceTest.java
Labels: ♻️Refactor

#89 !HOTFIX: notFoundDocCheck() 복원
  src/main/java/io/ejangs/docsa/domain/doc/app/DocService.java
Labels: 🔨Fix

#90 Refactor: `@AuthenticationPrincipal` 적용
  src/main/java/io/ejangs/docsa/domain/branch/api/BranchController.java
  src/main/java/io/ejangs/docsa/domain/commit/api/CommitController.java
  src/main/java/io/ejangs/docsa/domain/doc/api/DocController.java
  src/main/java/io/ejangs/docsa/domain/save/api/SaveController.java
  src/main/java/io/ejangs/docsa/domain/user/security/CustomUserDetails.java
  src/test/java/io/ejangs/docsa/domain/auth/api/AuthControllerTest.java
  src/test/java/io/ejangs/docsa/domain/branch/api/BranchControllerTest.java
  src/test/java/io/ejangs/docsa/domain/doc/unit/DocControllerUnitTests.java
  src/test/java/io/ejangs/docsa/domain/save/api/SaveControllerTest.java
  src/test/java/io/ejangs/docsa/global/security/WithCustomMockUser.java
  src/test/java/io/ejangs/docsa/global/security/WithCustomMockUserSecurityContextFactory.java
Labels: ♻️Refactor

#85 Feat: 병합하기 API
  src/main/java/io/ejangs/docsa/domain/block/app/BlockService.java
  src/main/java/io/ejangs/docsa/domain/branch/app/BranchService.java
  src/main/java/io/ejangs/docsa/domain/branch/entity/Branch.java
  src/main/java/io/ejangs/docsa/domain/commit/api/CommitController.java
  src/main/java/io/ejangs/docsa/domain/commit/app/CommitService.java
  src/main/java/io/ejangs/docsa/domain/commit/dto/CommitMongoIdsDto.java
  src/main/java/io/ejangs/docsa/domain/commit/dto/request/MergeCommitRequest.java
  src/main/java/io/ejangs/docsa/domain/commit/util/CommitMapper.java
  src/main/java/io/ejangs/docsa/domain/doc/dao/mysql/EdgeRepository.java
  src/main/java/io/ejangs/docsa/domain/doc/entity/Edge.java
  src/test/java/io/ejangs/docsa/domain/commit/app/CommitServiceMockTest.java
  src/test/java/io/ejangs/docsa/domain/commit/app/GetCommitMockTest.java
  src/test/java/io/ejangs/docsa/domain/commit/app/MergeCommitIntegrationTest.java
  src/test/java/io/ejangs/docsa/domain/commit/util/CommitIntegrationTestUtils.java
  src/test/java/io/ejangs/docsa/domain/commit/util/CommitMockTestUtils.java
Labels: 🧐Help wanted, ✨Feature

#84 Feat: 브랜치 삭제하기 API
  src/main/java/io/ejangs/docsa/domain/branch/api/BranchController.java
  src/main/java/io/ejangs/docsa/domain/branch/app/BranchService.java
  src/main/java/io/ejangs/docsa/domain/branch/dao/mysql/BranchRepository.java
  src/main/java/io/ejangs/docsa/domain/branch/entity/Branch.java
  src/main/java/io/ejangs/docsa/domain/commit/app/CommitService.java
  src/main/java/io/ejangs/docsa/domain/doc/dao/mysql/DocRepository.java
  src/main/java/io/ejangs/docsa/domain/doc/dao/mysql/EdgeRepository.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/BranchErrorCode.java
  src/main/java/io/ejangs/docsa/global/mongoDeleteSystem/util/MongoDeleteMapper.java
  src/test/java/io/ejangs/docsa/domain/branch/api/BranchControllerTest.java
  src/test/java/io/ejangs/docsa/domain/branch/app/BranchServiceTest.java
  src/test/resources/application.yml
Labels: ✨Feature

#101 Refactor: 문서 조회 페이지네이션 적용(메인/사이드바)
  src/main/java/io/ejangs/docsa/domain/doc/api/DocController.java
  src/main/java/io/ejangs/docsa/domain/doc/app/DocService.java
  src/main/java/io/ejangs/docsa/domain/doc/dao/mysql/DocRepository.java
  src/main/java/io/ejangs/docsa/domain/doc/model/PageDirectionType.java
  src/main/java/io/ejangs/docsa/domain/doc/model/PageSortType.java
  src/main/java/io/ejangs/docsa/domain/save/util/PageableFactory.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/PageErrorCode.java
  src/test/java/io/ejangs/docsa/domain/doc/integration/DocServiceIntegrationTests.java
  src/test/java/io/ejangs/docsa/domain/doc/unit/DocControllerUnitTests.java
  src/test/java/io/ejangs/docsa/domain/doc/unit/DocServiceUnitTests.java
  src/test/java/io/ejangs/docsa/domain/doc/util/DocTestUtils.java
  src/test/java/io/ejangs/docsa/mongoDeleteSystem/MongoTransactionTestService.java
  src/test/java/io/ejangs/docsa/mongoDeleteSystem/MongoTransactionTests.java
Labels: ♻️Refactor

#102 Docs: Branch 도메인 swagger 적용
  src/main/java/io/ejangs/docsa/domain/branch/api/BranchController.java
  src/main/java/io/ejangs/docsa/domain/branch/swagger/CreateBranchOrSaveDocs.java
  src/main/java/io/ejangs/docsa/domain/branch/swagger/RenameBranchDocs.java
Labels: 📄Documentation

#110 Refactor: CommitService에서 User관련 유효성 검사 추가
  src/main/java/io/ejangs/docsa/domain/commit/api/CommitController.java
  src/main/java/io/ejangs/docsa/domain/commit/app/CommitService.java
  src/main/java/io/ejangs/docsa/domain/commit/util/CommitMapper.java
  src/main/java/io/ejangs/docsa/domain/doc/app/DocService.java
  src/test/java/io/ejangs/docsa/domain/commit/app/CommitServiceMockTest.java
  src/test/java/io/ejangs/docsa/domain/commit/app/GetCommitMockTest.java
  src/test/java/io/ejangs/docsa/domain/commit/app/MergeCommitIntegrationTest.java
Labels: ♻️Refactor

#106 Fix: MultipleBagFetchException 임시 해결 (dto projection)
  src/main/java/io/ejangs/docsa/domain/branch/app/BranchService.java
  src/main/java/io/ejangs/docsa/domain/branch/dao/mysql/BranchRepository.java
  src/main/java/io/ejangs/docsa/domain/branch/dto/BranchDto.java
  src/main/java/io/ejangs/docsa/domain/commit/dao/mysql/CommitRepository.java
  src/main/java/io/ejangs/docsa/domain/commit/dto/CommitDto.java
  src/main/java/io/ejangs/docsa/domain/doc/app/DocService.java
  src/main/java/io/ejangs/docsa/domain/doc/dao/mysql/DocRepository.java
  src/main/java/io/ejangs/docsa/domain/doc/dao/mysql/EdgeRepository.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/EdgeDto.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/graph/GraphBranchDto.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/graph/GraphCommitDto.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/graph/GraphEdgeDto.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/response/CommitGraphResponse.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/response/DocTitleOnlyResponse.java
  src/main/java/io/ejangs/docsa/domain/doc/util/GraphMapper.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/BranchErrorCode.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/DocErrorCode.java
  src/test/java/io/ejangs/docsa/domain/branch/app/BranchServiceTest.java
  src/test/java/io/ejangs/docsa/domain/doc/integration/DocGraphIntegrationTest.java
  src/test/java/io/ejangs/docsa/domain/doc/unit/DocControllerUnitTests.java
  src/test/java/io/ejangs/docsa/domain/doc/unit/DocServiceUnitTests.java
  src/test/java/io/ejangs/docsa/domain/doc/util/DocTestUtils.java
Labels: 🐞Bug, 🧐Help wanted

#117 Feat: 문서제목 검색 API
  src/main/java/io/ejangs/docsa/domain/doc/api/DocController.java
  src/main/java/io/ejangs/docsa/domain/doc/app/DocService.java
  src/main/java/io/ejangs/docsa/domain/doc/dao/mysql/DocRepository.java
  src/main/java/io/ejangs/docsa/domain/doc/util/DocListAssembler.java
  src/test/java/io/ejangs/docsa/domain/doc/integration/DocServiceIntegrationTests.java
  src/test/java/io/ejangs/docsa/domain/doc/unit/DocServiceUnitTests.java
  src/test/java/io/ejangs/docsa/domain/doc/util/DocTestUtils.java
Labels: ✨Feature

#116 Feat: 기록 삭제 API 구현
  src/main/java/io/ejangs/docsa/domain/branch/app/BranchService.java
  src/main/java/io/ejangs/docsa/domain/branch/dao/mysql/BranchRepository.java
  src/main/java/io/ejangs/docsa/domain/branch/entity/Branch.java
  src/main/java/io/ejangs/docsa/domain/commit/api/CommitController.java
  src/main/java/io/ejangs/docsa/domain/commit/app/CommitService.java
  src/main/java/io/ejangs/docsa/domain/doc/app/EdgeService.java
  src/main/java/io/ejangs/docsa/domain/doc/dao/mysql/EdgeRepository.java
  src/main/java/io/ejangs/docsa/domain/doc/entity/Doc.java
  src/main/java/io/ejangs/docsa/domain/doc/entity/Edge.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/CommitErrorCode.java
  src/main/java/io/ejangs/docsa/global/mongo/deletion/util/MongoIdsCollector.java
  src/test/java/io/ejangs/docsa/domain/commit/app/DeleteCommitIntegrationTest.java
  src/test/java/io/ejangs/docsa/domain/commit/util/CommitIntegrationTestUtils.java
  src/test/java/io/ejangs/docsa/domain/commit/util/TestDocIntegrationDto.java
Labels: ✨Feature

#120 Feat: 세션 유효성 확인 API
  src/main/java/io/ejangs/docsa/domain/auth/api/AuthController.java
  src/main/java/io/ejangs/docsa/domain/auth/dto/response/SessionCheckResponse.java
  src/main/java/io/ejangs/docsa/domain/auth/swagger/CheckSessionDocs.java
  src/main/java/io/ejangs/docsa/domain/user/security/CustomAuthenticationEntryPoint.java
  src/main/java/io/ejangs/docsa/global/config/SecurityConfig.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/AuthErrorCode.java
  src/test/java/io/ejangs/docsa/domain/auth/api/integration/AuthIntegrationTest.java
Labels: ✨Feature

#128 Fix: 쿠키 전달을 위한 세팅 추가 및 수정
  src/main/java/io/ejangs/docsa/global/config/SecurityConfig.java
  src/main/resources/application-prod.yml
Labels: 🔨Fix

#125 Docs: Commit 도메인 Delete Commit에 swagger 적용
  src/main/java/io/ejangs/docsa/domain/commit/api/CommitController.java
  src/main/java/io/ejangs/docsa/domain/commit/swagger/DeleteCommitDocs.java
  src/main/java/io/ejangs/docsa/domain/doc/api/DocController.java
Labels: 📄Documentation

#129 Fix: Commit Service 에러 수정
  src/main/java/io/ejangs/docsa/domain/commit/app/CommitService.java
  src/main/java/io/ejangs/docsa/domain/commit/dto/MergeCommitDto.java
  src/main/java/io/ejangs/docsa/domain/commit/util/CommitMapper.java
  src/main/java/io/ejangs/docsa/domain/save/app/SaveService.java
  src/main/java/io/ejangs/docsa/global/mongo/deletion/util/MongoDeleteMapper.java
  src/test/java/io/ejangs/docsa/domain/commit/app/CommitServiceMockTest.java
  src/test/java/io/ejangs/docsa/domain/commit/app/CreateCommitIntegrationTest.java
  src/test/java/io/ejangs/docsa/domain/commit/util/CommitIntegrationTestUtils.java
  src/test/java/io/ejangs/docsa/domain/commit/util/TestCreateCommitRequestDto.java
  src/test/java/io/ejangs/docsa/domain/commit/util/TestInitDocIntegrationDto.java
Labels: 🔨Fix

#139 Refactor: 기록 병합하기 로직 수정
  src/main/java/io/ejangs/docsa/domain/commit/app/CommitService.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/CommitErrorCode.java
  src/test/java/io/ejangs/docsa/domain/commit/app/DeleteCommitIntegrationTest.java
  src/test/java/io/ejangs/docsa/domain/commit/app/MergeCommitIntegrationTest.java
  src/test/java/io/ejangs/docsa/domain/commit/util/CommitIntegrationTestUtils.java
Labels: ♻️Refactor

#145 Refactor: 이메일 관련 코드 수정
  build.gradle
  src/main/java/io/ejangs/docsa/domain/auth/app/AuthService.java
  src/main/java/io/ejangs/docsa/domain/auth/app/MailService.java
  src/main/java/io/ejangs/docsa/domain/auth/swagger/SendResetPwdCodeDocs.java
  src/main/java/io/ejangs/docsa/domain/auth/swagger/SendSignupCodeDocs.java
  src/main/java/io/ejangs/docsa/global/config/CacheConfig.java
  src/main/java/io/ejangs/docsa/global/config/MailConfig.java
  src/main/java/io/ejangs/docsa/global/config/MailProperties.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/AuthErrorCode.java
  src/main/resources/application.yml
  src/main/resources/static/img/docsa_logo.png
  src/main/resources/templates/code-mail.html
  src/test/java/io/ejangs/docsa/domain/auth/app/AuthServiceTest.java
Labels: ♻️Refactor

#148 Fix: 브랜치 생성시 이름 검증 에러처리 추가
  src/main/java/io/ejangs/docsa/domain/branch/app/BranchService.java
  src/main/java/io/ejangs/docsa/domain/branch/dao/mysql/BranchRepository.java
  src/main/java/io/ejangs/docsa/global/exception/errorcode/BranchErrorCode.java
  src/main/resources/application.yml
Labels: 🔨Fix

#151 Fix: main으로 yml 수정
  src/main/resources/application.yml
Labels: 🔨Fix

#153 Test: 테스트 편의성을 위한 세션 유효기간 임시 연장
  src/main/resources/application-prod.yml
Labels: 💡Test

#158 Docs: save swagger 변경
  src/main/java/io/ejangs/docsa/domain/save/api/SaveController.java
  src/main/java/io/ejangs/docsa/domain/save/swagger/DeleteSaveDocs.java
  src/main/java/io/ejangs/docsa/domain/save/swagger/GetSaveDocs.java
  src/main/java/io/ejangs/docsa/domain/save/swagger/UpdateSaveDocs.java
Labels: 📄Documentation

#162 Docs: Doc rename search swagger 수정
  src/main/java/io/ejangs/docsa/domain/commit/app/CommitContentAssembler.java
  src/main/java/io/ejangs/docsa/domain/doc/swagger/RenameDocDocs.java
  src/main/java/io/ejangs/docsa/domain/doc/swagger/SearchDocDocs.java
Labels: 📄Documentation

#165 Refactor: LocalDateTime으로 변환
  src/main/java/io/ejangs/docsa/domain/doc/dto/graph/GraphBranchDto.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/graph/GraphCommitDto.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/response/DocListResponse.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/response/DocListSimpleResponse.java
  src/main/java/io/ejangs/docsa/domain/doc/dto/response/DocTitleUpdateResponse.java
  src/main/java/io/ejangs/docsa/domain/save/dto/response/SaveGetResponse.java
  src/main/java/io/ejangs/docsa/domain/save/dto/response/SaveUpdateResponse.java
  src/main/java/io/ejangs/docsa/domain/save/util/SaveMapper.java
  src/test/java/io/ejangs/docsa/domain/doc/unit/DocServiceUnitTests.java
  src/test/java/io/ejangs/docsa/domain/save/api/SaveControllerTest.java
  src/test/java/io/ejangs/docsa/domain/save/app/SaveServiceUnitTest.java
Labels: ♻️Refactor
